[package]
name = "cc-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
cc-checker = { path = "../cc-checker" }
cc-cluster = { path = "../cc-cluster" }
cc-core = { path = "../cc-core" }
cc-sim = { path = "../cc-sim" }

[lints]
workspace = true

